# Generated by Django 5.0.2 on 2024-02-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('visiting_reason', models.TextField()),
                ('meet_for', models.CharField(max_length=100)),
            ],
        ),
    ]
